import type { AppData } from '../types'

// ============================================================
// DATOS POR DEFECTO — Editar aquí para cambiar datos iniciales
// ============================================================

export const SK = 'agenda-cls-stable'

export const DEFAULT_DATA: AppData = {
  nextId: 200,
  nextPagoId: 1000,
  nextInvId: 2000,
  deletedTaskIds: [],
  proyectos: [
    { id: 'arthouse',  nombre: 'Arthouse Tower',  color: '#2B5E3E' },
    { id: 'arthouse2', nombre: 'Arthouse 2',       color: '#1A5A8A' },
    { id: 'grid7',     nombre: 'Torre Grid 7',      color: '#8B4513' },
    { id: 'elspot',    nombre: 'El Spot',            color: '#6B2D8B' },
    { id: 'nomad',     nombre: 'Nomad',              color: '#8B1A4A' },
    { id: 'aqua4',     nombre: 'Aquamarina 4',       color: '#1A7A54' },
    { id: 'doorvitech',nombre: 'Doorvitech',         color: '#8B7A00' },
    { id: 'gorditos',  nombre: "Gordito's",           color: '#5A2D8B' },
    { id: 'cayaya',    nombre: 'Cayaya',              color: '#1A6B8A' },
  ],
  tareas: [
    { id: 1,  txt: 'Comprar adaptador USB-C a HDMI o DisplayPort', done: true,  proj: null,        prio: 'media', fecha: '', nota: '' },
    { id: 2,  txt: 'Responder a GEEKOM',                            done: false, proj: null,        prio: 'alta',  fecha: '', nota: '' },
    { id: 3,  txt: 'Revisar lo de Mario Walwyn',                    done: false, proj: null,        prio: 'media', fecha: '', nota: '' },
    { id: 9,  txt: 'Devolver dinero a Euripides',                   done: false, proj: 'grid7',     prio: 'alta',  fecha: '', nota: '' },
    { id: 4,  txt: "Hacer carta oferta de compra – Gordito's Fresh Mex", done: false, proj: 'gorditos', prio: 'alta', fecha: '', nota: '' },
    { id: 5,  txt: 'Organizar cotizaciones de Cayaya (están en la agenda de WhatsApp)', done: false, proj: 'cayaya', prio: 'media', fecha: '', nota: '' },
    { id: 6,  txt: 'Organizar diagramas de todos los proyectos',    done: true,  proj: 'doorvitech', prio: 'alta',  fecha: '', nota: '' },
    { id: 7,  txt: 'Enviar diagramas a Roni y Bryan para verificar cocinas y altura de closets', done: false, proj: 'doorvitech', prio: 'alta', fecha: '', nota: '' },
    { id: 8,  txt: 'Firmar y que pongan el pedido',                 done: false, proj: 'doorvitech', prio: 'alta',  fecha: '', nota: '' },
    { id: 10, txt: 'Recoger laser para María Amelia (en obra)',     done: true,  proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 11, txt: 'Ver ejemplo de ACM in situ (La Zurza)',         done: true,  proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 12, txt: 'Confirmar grosor ACM con mi hermano',           done: true,  proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 13, txt: 'Decidir alcance completo de fachada con mi hermano', done: true, proj: 'arthouse', prio: 'alta', fecha: '', nota: '' },
    { id: 14, txt: 'Pedirle cotización completa a Arturo según lo decidido', done: false, proj: 'arthouse', prio: 'media', fecha: '', nota: '' },
    { id: 15, txt: 'Confirmarle el grosor a Arturo',                done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 16, txt: 'Enviar avance de barandas a Máximo',            done: false, proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 17, txt: 'Verificar ancho nicho lavadora (75 cm)',        done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 18, txt: 'Verificar ancho puerta hacia techo (90 cm)',    done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 19, txt: 'Arrancar trabajos de fachada en densglass',     done: false, proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 20, txt: 'Arrancar porcelanato en balcones',              done: false, proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 21, txt: 'Medir m² de pisos para balcones',               done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 22, txt: 'Replantear jacuzzi',                            done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 23, txt: 'Ver descuadre en ventanas',                     done: true,  proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 24, txt: 'Diseño de vidrios fijos',                       done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 25, txt: 'Ver desagües de balcones con Tony',             done: true,  proj: 'arthouse',  prio: 'media', fecha: '', nota: '' },
    { id: 26, txt: 'Enviar planos sin balcón al MIVED',             done: false, proj: 'arthouse',  prio: 'alta',  fecha: '', nota: '' },
    { id: 30, txt: 'Enviar diagramas de cocinas a Adrián para que las ponga igual que el diagrama', done: false, proj: 'arthouse2', prio: 'alta', fecha: '', nota: '' },
    { id: 31, txt: 'Hacer correcciones en planta',                  done: false, proj: 'arthouse2', prio: 'media', fecha: '', nota: '' },
    { id: 40, txt: 'Enviar recibo a Yeriel Rosario – unidad 10B',   done: false, proj: 'grid7',     prio: 'alta',  fecha: '', nota: '' },
    { id: 41, txt: 'Verificar nueva reserva – unidad 11B',          done: false, proj: 'grid7',     prio: 'alta',  fecha: '', nota: '' },
    { id: 42, txt: 'Preparar render de planta para el comprador del 11B', done: true, proj: 'grid7', prio: 'alta', fecha: '', nota: '' },
    { id: 43, txt: 'Devolución al comprador de Murcia – transferencia + comprobante a Geraly', done: false, proj: 'grid7', prio: 'alta', fecha: '', nota: '' },
    { id: 44, txt: 'Terminar planos y subir a la VUC',              done: false, proj: 'grid7',     prio: 'alta',  fecha: '', nota: '' },
    { id: 50, txt: 'Verificar que el dinero de Fizjohn haya caído', done: false, proj: 'elspot',    prio: 'alta',  fecha: '', nota: '' },
    { id: 51, txt: 'Verificar que puertas de lavanderías se pongan de 90 cm', done: true, proj: 'elspot', prio: 'media', fecha: '', nota: '' },
    { id: 60, txt: 'Arrancar trabajo de amueblamiento con Patricia y María Amelia', done: false, proj: 'nomad', prio: 'alta', fecha: '', nota: '' },
    { id: 61, txt: 'Verificar status de cierre del cliente Guillaume Beaudoin', done: false, proj: 'nomad', prio: 'alta', fecha: '', nota: '' },
    { id: 70, txt: 'Verificar que el dinero de la venta haya caído en BHD', done: true, proj: 'aqua4', prio: 'alta', fecha: '', nota: '' },
  ],
  obligaciones: [
    { id: 'o1', txt: 'Tarjeta BHD Suertepas',       tipo: 'tarjeta'  },
    { id: 'o2', txt: 'Tarjeta BHD Personal',         tipo: 'tarjeta'  },
    { id: 'o3', txt: 'Tarjeta Banreservas Equipos',  tipo: 'tarjeta'  },
    { id: 'o4', txt: 'Tarjeta Popular',              tipo: 'tarjeta'  },
    { id: 'o5', txt: 'Préstamo Banreservas Personal',tipo: 'prestamo' },
    { id: 'o6', txt: 'Préstamo Banreservas Equipos', tipo: 'prestamo' },
    { id: 'o7', txt: 'Préstamo BHD Equipos',         tipo: 'prestamo' },
  ],
  pagos: [
    { id: 'p1', oblId: 'o1', mes: '2026-03', done: false, fecha: '2026-03-23' },
    { id: 'p2', oblId: 'o2', mes: '2026-03', done: false, fecha: '2026-03-26' },
    { id: 'p3', oblId: 'o3', mes: '2026-03', done: true,  fecha: '2026-03-21' },
    { id: 'p4', oblId: 'o4', mes: '2026-03', done: false, fecha: '2026-03-29' },
    { id: 'p5', oblId: 'o5', mes: '2026-03', done: true,  fecha: ''           },
    { id: 'p6', oblId: 'o6', mes: '2026-03', done: true,  fecha: ''           },
    { id: 'p7', oblId: 'o7', mes: '2026-03', done: true,  fecha: '2026-04-13' },
  ],
  eventos: [],
  inversiones: [
    { id: 'i1',  nombre: 'Arthouse Tower',    cat: 'inmobiliario', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Proyecto en construcción, Santiago' },
    { id: 'i2',  nombre: 'Torre Grid 7',       cat: 'inmobiliario', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Proyecto en construcción, Santiago' },
    { id: 'i3',  nombre: 'El Spot',            cat: 'inmobiliario', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Proyecto Perla Marina, Sosúa' },
    { id: 'i4',  nombre: 'Nomad',              cat: 'inmobiliario', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Proyecto Sosúa' },
    { id: 'i5',  nombre: 'The Shore',          cat: 'inmobiliario', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Playa Alicia Holdings, Sosúa' },
    { id: 'i6',  nombre: 'Terreno Jamao',      cat: 'inmobiliario', moneda: 'DOP', compra: 0, actual: 0, fecha: '', nota: 'Potencial eco-lodge' },
    { id: 'i7',  nombre: 'Mercedes GLS',       cat: 'vehiculos',    moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: '' },
    { id: 'i8',  nombre: 'Porsche Cayenne',    cat: 'vehiculos',    moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: '' },
    { id: 'i9',  nombre: 'Can-Am Maverick Trail', cat: 'vehiculos', moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'UTV' },
    { id: 'i10', nombre: 'Dolcevita Spain S.L.', cat: 'empresas',   moneda: 'USD', compra: 0, actual: 0, fecha: '', nota: 'Co-administrador con María Amelia' },
  ],
}
